# Generated by Django 5.2.1 on 2025-06-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
