# Generated by Django 4.1.13 on 2025-06-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
